const CategoryListTypeA = [
  { emoji: "🤣 ", name: "유머게시판" },
  { emoji: "⚽️ ", name: "해외축구" },
  { emoji: "📈 ", name: "주식투자" },
  { emoji: "🎮 ", name: "게임" },
  { emoji: "💸 ", name: "비트코인" },
  { emoji: "🖋 ", name: "만화/애니" },
  { emoji: "📹 ", name: "인터넷방송" },
  //{ emoji: "🔫 ", name: "나때는군대" },
  //{ emoji: "🛩 ", name: "여행먹방" },
  { emoji: "🐶 ", name: "자유게시판" },
];

// list of items
const CategoryListTypeB = [
  { name: "👑 실시간 인기글" },
  { name: "🤣 유머게시판" },
  { name: "⚽️ 해외축구" },
  { name: "📈 주식투자" },
  { name: "🎮 게임" },
  { name: "💸 비트코인" },
  { name: "🖋 만화/애니" },
  { name: "📹 인터넷방송" },
  //{ name: "🔫 나때는군대" },
  //{ name: "🛩 여행먹방" },
  { name: "🐶 자유게시판" },
];

const CategoryListTypeC = [
  { name: "🤣 유머게시판", key: "유머게시판" },
  { name: "⚽️ 해외축구", key: "해외축구" },
  { name: "📈 주식투자", key: "주식투자" },
  { name: "🎮 게임", key: "게임" },
  { name: "💸 비트코인", key: "비트코인" },
  { name: "🖋 만화/애니", key: "만화/애니" },
  { name: "📹 인터넷방송", key: "인터넷방송" },
  //{ name: "🔫 나때는군대", key: "나때는군대" },
  //{ name: "🛩 여행먹방", key: "여행먹방" },
  { name: "🐶 자유게시판", key: "자유게시판" },
];

const removeEmojis = (str) => {
  const regex = /(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|\ud83c[\ude32-\ude3a]|\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])/g;
  return str.replace(regex, "").replace(" ", "");
};

const getImages = (data) => {
  var m,
    urls = [],
    // eslint-disable-next-line no-useless-escape
    rex = /<img[^>]*src=[\"']?([^>\"']+)[\"']?[^>]*>/g;

  while ((m = rex.exec(data))) {
    urls.push(m[1]);
  }

  return urls;
};

const getIp = async () => {
  const publicIp = require("public-ip");
  const ip = await publicIp.v4();
  const splitResult = ip.split(".");
  const result = splitResult[0] + "." + splitResult[1];
  return result;
};

const getFullIp = async () => {
  const publicIp = require("public-ip");
  const ip = await publicIp.v4();
  return ip;
};

const checkValidate = (data, alert) => {
  alert.removeAll();

  var result = true;
  for (var i = 0; i < data.length; i++) {
    if (
      data[i].key === undefined ||
      data[i].key === null ||
      data[i].key === ""
    ) {
      alert.error(data[i].tagNull);
      result = false;
    } else if (
      data[i].regex !== undefined &&
      !data[i].regex.test(data[i].key)
    ) {
      alert.error(data[i].tagRegex);
      result = false;
    }
  }
  return result;
};

const getLevel = (point) => {
  return Math.floor(Math.sqrt(point) / 4);
};

const getPercentage = (point) => {
  return (Math.sqrt(point) / 4 - Math.floor(Math.sqrt(point) / 4)) * 100;
};

const getRemain = (point) => {
  return (getLevel(point) + 1) * 4 * (getLevel(point) + 1) * 4 - point;
};

const footerDataPrivacy = `<p ><strong><span style='font-size:16px;'>리얼시티 개인정보 처리방침</span></strong></p>
<p ><span style='font-size:16px;'>정보통신망 이용촉진 등에 관한 법률 등 관련 법률에 의한 개인정보 보호규정 및 정보통신부가 제정한 개인정보지침을 준수하고 있습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>1.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 수집 항목</span></strong></p>
<p ><span style='font-size:16px;'>원활한 서비스 이용과 고객과의 소통을 위해 수집합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>필수항목</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>아이디</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>비밀번호</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>이메일</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>자동수집항목</span><span style='font-size:16px;'>: IP&nbsp;</span><span style='font-size:16px;'>주소</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>접속 기록</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>쿠키 등</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>2.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 수집 방법</span></strong></p>
<p ><span style='font-size:16px;'>회원 가입 시에 필수항목 기재를 요청합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>3.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 수집 이용 목적</span></strong></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>아이디</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>비밀번호</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>이메일</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>회원 가입시에 사용자확인</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>중복가입 방지</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>부정 이용 방지를 위한 목적으로 사용합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>이용자의</span><span style='font-size:16px;'>&nbsp;IP&nbsp;</span><span style='font-size:16px;'>주소</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>접속 기록 등</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>불량회원의 부정 이용방지와 비인가 사용방지</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>통계학적 분석에 사용합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>4.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보 공유 및 제공</span></strong></p>
<p ><span style='font-size:16px;'>회원의 동의가 있거나 법률의 규정 또는 수사목적으로 법령에 정해진 절차와 방법에 따른 수사기관의 요구에 의한 경우를 제외하고</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>어떠한 경우에도 본 방침을 넘어 이용자의 개인정보를 이용하거나 외부에 공개하지 않습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>대한민국 경찰서에서 통신자료제공 요청이 온 경우에는 개인정보를 경찰서에 제공합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>5.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 위탁</span></strong></p>
<p ><span style='font-size:16px;'>회원의 동의 없이 개인정보를 외부에 위탁하지 않습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>6.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 보유 및 이용기간</span></strong></p>
<p ><span style='font-size:16px;'>-&nbsp;</span><span style='font-size:16px;'>가입 회원정보는 탈퇴할 시</span><span style='font-size:16px;'>&nbsp;3</span><span style='font-size:16px;'>년간 보관 후 파기됩니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>-&nbsp;</span><span style='font-size:16px;'>단</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>게시물 및 댓글의 내용은 사이트 폐쇄 시까지 보관합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>-&nbsp;</span><span style='font-size:16px;'>악성 사용자 재가입을 막기 위해</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>단일 암호화 기법으로 해쉬 방식으로 일부 개인정보의 해쉬를 영구적으로 저장하여 가입 제한을 할 수 있다</span><span style='font-size:16px;'>(</span><span style='font-size:16px;'>이 때 개인정보 자체는 저장되지 않음</span><span style='font-size:16px;'>).</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>7.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 파기절차 및 방법</span></strong></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>파기절차</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>가입 회원정보는 탈퇴 후</span><span style='font-size:16px;'>&nbsp;3</span><span style='font-size:16px;'>년간 보관한 후</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>어떠한 용도로도 열람 또는 이용할 수 없도록 파기 처리합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>파기 방법</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>기록을 재생할 수 없는 기술적 방법을 사용하여 삭제합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>8.&nbsp;</span></strong><strong><span style='font-size:16px;'>이용자 및 법정대리인의 권리와 그 행사방법</span></strong></p>
<p ><span style='font-size:16px;'>이용자 및 법정 대리인은 언제든지 등록되어 있는 자신 혹은 당해 만</span><span style='font-size:16px;'>&nbsp;14</span><span style='font-size:16px;'>세 미만 아동의 개인정보를 조회하거나 수정할 수 있으며 가입해지를 요청할 수도 있습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>9.&nbsp;</span></strong><strong><span style='font-size:16px;'>쿠키</span></strong><strong><span style='font-size:16px;'>(Cookie)</span></strong><strong><span style='font-size:16px;'>의 설치</span></strong><strong><span style='font-size:16px;'>,&nbsp;</span></strong><strong><span style='font-size:16px;'>운영 및 거부</span></strong></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>쿠키</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>웹 사이트를 운영하는데 이용되는 서버가 사용자의 브라우저에 보내는 정보 파일로 사용자의 컴퓨터 하드디스크에 저장되기도 합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>쿠키 등의 사용 목적</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>사이트 로그인을 위한 아이디 식별 및 사이트 설정 기능이 담겨져 있어서 최적화된 정보 제공을 위해 사용합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>쿠키 설정 거부 방법</span><span style='font-size:16px;'>: (IE</span><span style='font-size:16px;'>의 경우</span><span style='font-size:16px;'>)&nbsp;</span><span style='font-size:16px;'>웹 브라우저 상단의 도구</span><span style='font-size:16px;'>&gt;</span><span style='font-size:16px;'>인터넷 옵션</span><span style='font-size:16px;'>&gt;&nbsp;</span><span style='font-size:16px;'>사이트별 개인정보에서 거부할 수 있습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>10.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보의 기술적</span></strong><strong><span style='font-size:16px;'>/</span></strong><strong><span style='font-size:16px;'>관리적 보호 대책</span></strong></p>
<p ><span style='font-size:16px;'>이용자들의 개인정보를 취급함에 있어 개인정보가 분실</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>도난</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>누출</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>변조 또는 훼손되지 않도록 안전성 확보를 위하여 다음과 같은 기술적</span><span style='font-size:16px;'>/</span><span style='font-size:16px;'>관리적 대책을 강구하고 있습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>비밀번호 암호화</span></p>
<p ><span style='font-size:16px;'>회원 아이디</span><span style='font-size:16px;'>(ID)</span><span style='font-size:16px;'>의 비밀번호는 암호화되어 저장 및 관리되고 있어 본인만이 알고 있으며</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>개인정보의 확인 및 변경도 비밀번호를 알고 있는 본인에 의해서만 가능합니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>해킹 등에 대비한 대책</span></p>
<p ><span style='font-size:16px;'>해킹이나 컴퓨터 바이러스 등에 의해 회원의 개인정보가 유출되거나 훼손되는 것을 막기 위해 최선을 다하고 있습니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>11.&nbsp;</span></strong><strong><span style='font-size:16px;'>개인정보 관리 책임자</span></strong></p>
<p ><span style='font-size:16px;'>-&nbsp;</span><span style='font-size:16px;'>개인정보 보호업무 부서</span><span style='font-size:16px;'>:&nbsp;</span><span style='font-size:16px;'>리얼시티 개인정보 보호팀</span></p>
<p ><span style='font-size:16px;'>-&nbsp;</span><span style='font-size:16px;'>연락처 및 이메일</span><span style='font-size:16px;'>&nbsp;: real_city_kr@naver.com</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>12.&nbsp;</span></strong><strong><span style='font-size:16px;'>고지의 의무</span></strong></p>
<p ><span style='font-size:16px;'>이 개인정보 취급방침이 법령</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>정책 또는 보안기술의 변경에 따라 내용이 추가</span><span style='font-size:16px;'>,&nbsp;</span><span style='font-size:16px;'>삭제 및 수정될 경우에는 변경사항의 시행일의</span><span style='font-size:16px;'>&nbsp;7</span><span style='font-size:16px;'>일전부터 사이트에 공고할 것입니다</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>공고일자</span><span style='font-size:16px;'>: 2021</span><span style='font-size:16px;'>년&nbsp;</span><span style='font-size:16px;'>1</span><span style='font-size:16px;'>월&nbsp;</span><span style='font-size:16px;'>22</span><span style='font-size:16px;'>일</span></p>
<p ><span style='font-size:16px;'>&bull;&nbsp;</span><span style='font-size:16px;'>시행일자</span><span style='font-size:16px;'>: 2021</span><span style='font-size:16px;'>년&nbsp;</span><span style='font-size:16px;'>1</span><span style='font-size:16px;'>월</span><span style='font-size:16px;'>&nbsp;22</span><span style='font-size:16px;'>일</span></p>
<p >&nbsp;</p>`;

const footerDataService = `<p ><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>대한민국의 진짜 이야기 리얼시티 커뮤니티는 뛰어난 접근성으로 유저들에게 소통할 수 있는 장을 인터넷에 제공합니다</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>.</span></p>
<p >&nbsp;</p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>주요서비스</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>게시판</span></strong></p>
<p ><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>&bull;&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>여러 개의 게시판을 유저의 취향대로 골라서 동시이용이 가능합니다</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>게임</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>스포츠</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>군대</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>유머</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>자유 등 다양한 게시판들이 있습니다</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>.</span></p>
<p >&nbsp;</p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>커뮤니티 포인트</span></strong></p>
<p ><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>&bull;&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>유저가 작성한 글과 댓글에 달린 좋아요를 바탕으로 커뮤니티 포인트가 쌓이며 이를 레벨로서 표기합니다</span></p>
<p >&nbsp;</p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>인생역전</span></strong></p>
<p ><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>&bull;&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>인생역전이라는 포인트 업그레이드 기능으로 유저가 커뮤니티 포인트를 걸고 일주에 한번 게임이 가능합니다</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>.</span></p>
<p >&nbsp;</p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>모바일 웹</span></strong></p>
<p ><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>&bull;&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>현 사이트는&nbsp;</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>PC</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>뿐만 아니라 모바일에서도 서비스를 제공합니다</span><span style='font-size:16px;line-height:107%;font-family:"굴림",sans-serif;'>.</span></p>`;

const footerDataRule = `<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>1</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>목적</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>본 약관은 리얼시티</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>이하</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>라 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>가 제공하는 리얼시티 및 리얼시티 관련 제반 서비스</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>이하</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>서비스</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>라 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>의 이용과 관련하여 회사와 회원과의 권리</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>의무 및 책임사항</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 필요한 사항을 규정함을 목적으로 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>2</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원의 정의</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회원이란 회사가 제공하는 서비스에 접속하여 본 약관에 따라 회사의 이용절차에 동의하고 회사가 제공하는 서비스를 이용하는 이용자를 말합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원 가입</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회원이 되고자 하는 자는 회사가 정한 가입 양식에 따라 회원정보를 기입하고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>동의</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;, &quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>확인</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>등의 버튼을 누르는 방법으로 회원 가입을 신청합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회사는 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>1</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항과 같이 회원으로 가입할 것을 신청한 자가 다음 각 호에 해당하지 않는 한 신청한 자를 회원으로 등록합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;1.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>등록 내용에 허위</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기재누락</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>오기가 있는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;2.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>6</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>조 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>2</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에 해당하는 회원 자격 제한 및 정지</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>상실을 한 경험이 있었던 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;3.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 회원으로 등록하는 것이 회사의 서비스 운영 및 기술상 현저히 지장이 있다고 판단되는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회원가입계약의 성립시기는 회사의 승낙이 가입신청자에게 도달한 시점으로 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>④ 회원은 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>1</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항의 회원정보 기재 내용에 변경이 발생한 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>즉시 변경사항을 정정하여 기재하여야 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>4</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>서비스의 제공 및 변경</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사는 회원에게 아래와 같은 서비스를 제공합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;1.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>커뮤니티 서비스</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;2.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>검색 서비스</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;3.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 회사가 자체 개발하거나 다른 회사와의 협력계약 등을 통해 회원들에게 제공할 일체의 서비스</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회사는 서비스의 내용 및 제공일자를 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>7</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>조 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>2</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에서 정한 방법으로 회원에게 통지하고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>1</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에 정한 서비스를 변경하여 제공할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>5</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>서비스의 중단</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사는 컴퓨터 등 정보통신설비의 보수점검&middot;교체 및 고장</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>통신의 두절 등의 사유가 발생한 경우에는 서비스의 제공을 일시적으로 중단할 수 있고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>새로운 서비스로의 교체</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 회사가 적절하다고 판단하는 사유에 기하여 현재 제공되는 서비스를 완전히 중단할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>1</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에 의한 서비스 중단의 경우에 회사는 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>7</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>조 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>2</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에서 정한 방법으로 회원에게 통지합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다만</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사가 통제할 수 없는 사유로 인한 서비스의 중단</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>시스템 관리자의 고의</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>과실이 없는 디스크 장애</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>시스템 다운 등</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>으로 인하여 사전 통지가 불가능한 경우에는 그러하지 아니합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>6</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원 탈퇴 및 자격 상실 등</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회원은 회사에 언제든지 자신의 회원 등록 말소</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원 탈퇴</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>를 요청할 수 있으며 회사는 위 요청을 받은 즉시 해당 회원의 회원 등록 말소를 위한 절차를 밟습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 탈퇴할 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>커뮤니티 서비스</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 공용 게시판 등에 등록된 게시물은 자동 삭제되지 않습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>특히</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>추천</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>/</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>비추천 기록은 공공의 목적 때문에 삭제 처리가 불가능합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회원이 다음 각 호의 사유에 해당하는 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 회원의 회원자격을 적절한 방법으로 제한 및 정지</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>상실시킬 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;1.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>가입 신청 시에 허위 내용을 등록한 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;2.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다른 사람의 서비스 이용을 방해하거나 그 정보를 도용하는 등 전자거래질서를 위협하는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;3.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>서비스를 이용하여 법령과 본 약관이 금지하거나 공서양속에 반하는 행위를 하는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>④ 회사가 회원의 회원자격을 상실시키기로 결정한 경우에는 회원등록을 말소합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>⑤ 이용자가 본 약관에 의해서 회원 가입 후 서비스를 이용하는 도중</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>연속하여</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;1</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>년 동안 서비스를 이용하기 위해 로그인 기록이 없는 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 회원의 회원자격을 상실시킬 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>7</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원에 대한 통지</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사가 특정 회원에게 서비스에 관한 통지를 하는 경우 회원정보에 등록된 메일주소를 사용할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회사가 불특정다수 회원에 대한 통지를 하는 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;7</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>일 이상 공지사항 게시판에 게시함으로써 개별 통지에 갈음할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>8</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원의 개인정보</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 서비스를 제공하기 위하여 관련 법령의 규정에 따라 회원으로부터 필요한 개인정보를 수집합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>. (</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개인정보에 대한 개별 항목은 개인정보취급방침에서 고지</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>9</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사의 의무</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사는 법령과 본 약관이 금지하거나 공서양속에 반하는 행위를 하지 않으며 본 약관이 정하는 바에 따라 지속적이고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>안정적으로 서비스를 제공하기 위해서 노력합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회사는 회원이 안전하고 편리하게 서비스를 이용할 수 있도록 시스템을 구축합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회사는 회원이 서비스를 이용함에 있어 회원에게 손해를 배상할 책임이 없습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>10</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원의</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;ID&nbsp;</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>및 비밀번호에 대한 의무</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사가 관계법령</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>, &quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개인정보보호정책</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>에 의해서 그 책임을 지는 경우를 제외하고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자신의</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;ID</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>와 비밀번호에 관한 관리책임은 각 회원에게 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회원은 자신의</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;ID&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>및 비밀번호를 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자에게 이용하게 해서는 안됩니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회원은 자신의</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;ID&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>및 비밀번호를 도난당하거나 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자가 사용하고 있음을 인지한 경우에는 바로 회사에 통보하고 회사의 안내가 있는 경우에는 그에 따라야 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>11</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원의 의무</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회원은 다음 각 호의 행위를 하여서는 안됩니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;1.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원가입신청 또는 변경시 허위내용을 등록하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;2.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사 및 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자의 지적재산권을 침해하거나 회사의 권리와 업무 또는 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자의 권리와 활동를 방해하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;3.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다른 회원의</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;ID</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>를 도용하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;4.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>관련 법령에 의하여 전송 또는 게시가 금지되는 정보</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>컴퓨터 프로그램 등</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>의 게시 또는 전송하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;5.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사의 직원 또는 서비스의 관리자를 가장하거나 타인의 명의를 도용하여 정보를 게시</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전송하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;6.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>컴퓨터 소프트웨어</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>하드웨어</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전기통신 장비의 정상적인 가동을 방해</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>파괴할 목적으로 고안된 소프트웨어 바이러스</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 다른 컴퓨터 코드</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>파일</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>프로그램을 포함하고 있는 자료를 게시하거나 전송하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;7.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다른 회원에 대한 개인정보를 그 동의 없이 수집</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>저장</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>공개하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;8.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>불특정 다수의 자를 대상으로 하여 광고 또는 선전을 게시하거나 음란물을 게시하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;9. ID</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>를</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;2</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개 이상 사용하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;10.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>추천 및 조회수 조작하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;11.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>게시판 글이나 댓글 도배</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;12.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 상식적인</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>악성</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>영업방해 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;13.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사가 제공하는 관련 서비스에 게시된 공지사항 규정을 위반하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;14.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>서버나 회선에 무리를 줄 수 있는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;15.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>사람의 직접적인 행동이 아닌 자동화된 프로그램이나 봇을 통해 로그인 및 로그인된 사용자가 하는 기능들을 이용하는 행위 또는 사이트 내용을 추출해서 광고를 제거해서 다시 제공하는 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>1</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에 해당하는 행위를 한 회원이 있을 경우 회사는 본 약관 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>6</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>조 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>2, 3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>항에서 정한 바에 따라 회원의 회원자격을 적절한 방법으로 제한 및 정지</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>상실시킬 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원 자격이 상실된 경우에는 해당 사용자의 글을 삭제할 의무가 회사에게 없습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회원은 그 귀책사유로 인하여 회사나 다른 회원이 입은 손해를 배상할 책임이 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>12</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>공개게시물의 삭제 또는 이용제한</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회원의 공개게시물의 내용이 다음 각 호에 해당하는 경우 회사는 해당 공개게시물에 회원에게 사전 통지 없이 해당 공개게시물을 삭제 또는 변경할 수 있고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>해당 회원의 회원 자격을 제한</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>정지 또는 상실시킬 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;1.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다른 회원 또는 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자를 비방하거나 중상 모략으로 명예를 손상시키는 내용</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;2.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>음란물</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>욕설 등 공서양속에 위반되는 내용의 정보</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>문장</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>도형 등을 유포하는 내용</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;3.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>범죄행위와 관련이 있다고 판단되는 내용</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;4.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다른 회원 또는 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자의 저작권 등 기타 권리를 침해하는 내용</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;5.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>종교적</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>정치적 분쟁을 야기하는 내용으로서</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>이러한 분쟁으로 인하여 회사의 업무가 방해되거나 방해되리라고 판단되는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;6.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>타인의 개인정보</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>사생활을 침해하거나 명예를 손상시키는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;7.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>동일한 내용을 중복하여 다수 게시하는 등 게시의 목적에 어긋나는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;8.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>불필요하거나 승인되지 않은 광고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>판촉물을 게재하는 경우</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;9.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>반복적인 내용이나 무의미한 도배성 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;10.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 상식적인</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;&quot;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>악성</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&quot;&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>영업방해 행위</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회원의 공개게시물로 인한 법률상 이익 침해를 근거로</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>다른 회원 또는 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자가 회원 또는 회사를 대상으로 하여 민형사상의 법적 조치</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>예</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>:</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>고소</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>가처분신청</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>손해배상청구소송</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>를 취하는 동시에 법적 조치와 관련된 게시물의 삭제를 요청해오는 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 동 법적 조치의 결과</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>(</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>예</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>:&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>검찰의 기소</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>법원의 가처분결정</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>손해배상판결</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>가 있을 때까지 관련 게시물에 대한 접근을 잠정적으로 제한할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회사는 서비스 악용 방지를 위해 일부 게시물에 대해 수정 및 삭제 가능 여부를 제한할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>13</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>저작권의 귀속 및 게시물의 이용</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사가 작성한 저작물에 대한 저작권</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 지적재산권은 회사에 귀속합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회원은 회사가 제공하는 서비스를 이용함으로써 얻은 정보를 회사의 사전승낙 없이 복제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전송</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>출판</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>배포</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>방송</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>기타 방법에 의하여 영리목적으로 이용하거나 제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>3</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>자에게 이용하게 하여서는 안됩니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회원이 서비스 내에 게시한 게시물의 저작권은 게시한 회원에게 귀속됩니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>단</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 서비스의 운영</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전시</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전송</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>배포</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>홍보의 목적으로 회원의 별도의 허락 없이 무상으로 저작권법에 규정하는 공정한 관행에 합치되게 합리적인 범위 내에서 다음과 같이 회원이 등록한 게시물을 사용할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;1.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>서비스 내에서 회원 게시물의 복제</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>수정</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개조</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전시</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전송</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>배포 및 저작물성을 해치지 않는 범위 내에서의 편집 저작물 작성</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;2.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>미디어</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>통신사 등 서비스 제휴 파트너에게 회원의 게시물 내용을 제공</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전시 혹은 홍보하게 하는 것</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>단</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>이 경우 회사는 별도의 동의 없이 회원의 이용자</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>ID&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>외에 회원의 개인정보를 제공하지 않습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;3.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 전항 이외의 방법으로 회원의 게시물을 이용하고자 하는 경우</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전화</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>팩스</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전자우편 등의 방법을 통해 사전에 회원의 동의를 얻어야 합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp; &nbsp; &nbsp;4.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사는 법적인 제한이 있는 글이 아니라면 사용자의 게시물을 삭제할 의무가 없습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>14</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>광고게재 및 광고주와의 거래</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사가 회원에게 서비스를 제공할 수 있는 서비스 투자기반의 일부는 광고게재를 통한 수익으로부터 나옵니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원은 회원이 등록한 게시물의 내용을 활용한 광고게재 및 기타 서비스상에 노출되는 광고게재에 대해 동의합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 회사는 서비스상에 게재되어 있거나 서비스를 통한 광고주의 판촉활동에 회원이 참여하거나 교신 또는 거래를 함으로써 발생하는 손실과 손해에 대해 책임을 지지 않습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회사는 회원의 글 링크를 회사의 제휴링크 코드로 변환이 가능합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>15</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>약관의 개정</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 회사는 약관의규제등에관한법률</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전자거래기본법</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>전자서명법</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>정보통신망이용촉진등에관한법률 등 관련법을 위배하지 않는 범위에서 본 약관을 개정할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 다만</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개정 내용이 회원에게 불리할 경우에는 적용일자</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;5</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>일 이전부터 적용일자 전일까지 공지합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>③ 회원은 변경된 약관에 대해 거부할 권리가 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원은 변경된 약관이 공지된 후</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;14</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>일 이내에 거부의사를 표명할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>회원이 거부하는 경우 회사는 당해 회원과의 계약을 해지할 수 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>만약 회원이 변경된 약관이 공지된 후</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;14</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>일 이내에 거부의사를 표시하지 않는 경우에는 동의하는 것으로 간주합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>제</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>16</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>조</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;(</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>재판관할</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>)</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>회사와 회원간에 발생한 서비스 이용에 관한 분쟁에 대하여는 대한민국 법을 적용하며</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>,&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>본 분쟁으로 인한 소는 민사소송법상의 관할을 가지는 대한민국의 법원에 제기합니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;text-align:justify;line-height:107%;font-size:13px;font-family:"맑은 고딕",sans-serif;'>&nbsp;</p>`;

const footerDataProtect = `<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>리얼시티 청소년보호정책</span></strong></p>
<p ><strong><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></strong></p>
<p ><strong><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>개요</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>리얼시티는 모든 연령대가 자유롭게 이용할 수 있는 공간으로써 유해 정보로부터 청소년을 보호하고</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>청소년의 안전한 인터넷 사용을 돕기 위해 노력하고 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>청소년 보호장치</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>-&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>리얼시티는 청소년이 아무런 제한장치 없이 청소년 유해정보에 노출되지 않도록 컨텐츠에 대한 관리에 관한</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>사전 및 사후 안전 장치를 마련해서 청소년 유해정보가 노출되지 않기 위한 예방차원의 조치를 취하고 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>청소년보호 책임자 및 담당자의 소속</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>-</span></strong><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>성명 및 연락처</span></strong></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>-&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>리얼시티는 청소년들이 좋은 정보를 안전하게 이용할 수 있도록 최선을 다하고 있습니다</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>.</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>① 청소년보호 책임자</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>-&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>직책</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;:&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개인정보 보호책임자</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>-&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>이메일</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;: &ldquo;real_city_kr@naver.com&rdquo;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>② 청소년보호 담당부서</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>-&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>직책</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;:&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>개인정보 보호책임자</span></p>
<p ><span style='font-size:16px;font-family:"굴림",sans-serif;'>-&nbsp;</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>이메일</span><span style='font-size:16px;font-family:"굴림",sans-serif;'>&nbsp;: &ldquo;real_city_kr@naver.com&rdquo;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;text-align:justify;line-height:107%;font-size:13px;font-family:"맑은 고딕",sans-serif;'>&nbsp;</p>`;

const footerDataContact = `<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>리얼시티 고객센터</span></strong></p>
<p ><strong><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></strong></p>
<p ><strong><span style='font-size:20px;font-family:"돋움",sans-serif;color:black;'>운영자 이메일</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>운영정책, 사용자관리, 광고문의 문의사항은 이쪽으로 연락주시기 바랍니다.</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>real_city_kr@naver.com</span></strong></p>
<p ><strong><span style='font-size:12px;font-family:"돋움",sans-serif;color:black;'>&nbsp;</span></strong></p>
<p ><strong><span style='font-size:20px;font-family:"돋움",sans-serif;color:black;'>개발자 이메일</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>버그 및 시스템 관련 문의는 이쪽으로 연락주시기 바랍니다.</span></strong></p>
<p ><strong><span style='font-size:16px;font-family:"굴림",sans-serif;'>Real.City.Korea@gmail.com</span></strong></p>`;

const dataMarketing = `<p ><strong><span style='font-size:16px;'>리얼시티 마케팅정보 수신동의</span></strong></p>
<p ><span style='font-size:16px;'>개인정보보호법 제22조 제4항에 의해 선택정보 사항에 대해서는 기재하지 않으셔도 서비스를 이용하실 수 있습니다.</span><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>&nbsp;</span></p>
<p ><strong><span style='font-size:16px;'>① 마케팅 및 광고에의 활용</span></strong><span style='font-size:16px;'>.</span></p>
<p ><span style='font-size:16px;'>신규 서비스(제품) 개발 및 맞춤 서비스 제공, 이벤트 및 광고성 정보 제공 및 참여기회 제공, 인구통계학적 특성에 따른 서비스 제공 및 광고 게재, 서비스의 유효성 확인, 접속빈도 파악 또는 회원의 서비스 이용에 대한 통계 등을 목적으로 개인정보를 처리합니다.</span><span style='font-size:16px;'>.</span></p>`;

export {
  CategoryListTypeA,
  CategoryListTypeB,
  CategoryListTypeC,
  removeEmojis,
  getImages,
  getIp,
  getFullIp,
  checkValidate,
  getLevel,
  getPercentage,
  getRemain,
  footerDataPrivacy,
  footerDataService,
  footerDataRule,
  footerDataProtect,
  footerDataContact,
  dataMarketing,
};
